<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>DaveTheDiverMP</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="0Harmony" HintPath="..\DAVE THE DIVER\BepInEx\core\0Harmony.dll" Private="false" />
    <Reference Include="BepInEx.Core" HintPath="..\DAVE THE DIVER\BepInEx\core\BepInEx.Core.dll" Private="false" />
    <Reference Include="BepInEx.Unity.Common" HintPath="..\DAVE THE DIVER\BepInEx\core\BepInEx.Unity.Common.dll" Private="false" />
    <Reference Include="BepInEx.Unity.IL2CPP" HintPath="..\DAVE THE DIVER\BepInEx\core\BepInEx.Unity.IL2CPP.dll" Private="false" />
    <Reference Include="Il2CppInterop.Runtime" HintPath="..\DAVE THE DIVER\BepInEx\core\Il2CppInterop.Runtime.dll" Private="false" />
    <Reference Include="Assembly-CSharp" HintPath="..\DAVE THE DIVER\BepInEx\interop\Assembly-CSharp.dll" Private="false" />
    <Reference Include="Il2Cppmscorlib" HintPath="..\DAVE THE DIVER\BepInEx\interop\Il2Cppmscorlib.dll" Private="false" />
    <Reference Include="InputSystemWrapper" HintPath="..\DAVE THE DIVER\BepInEx\interop\InputSystemWrapper.dll" Private="false" />
    <Reference Include="Steamworks.NET" HintPath="..\DAVE THE DIVER\BepInEx\interop\com.rlabrecque.steamworks.net.dll" Private="false" />
    <Reference Include="UnityEngine.CoreModule" HintPath="..\DAVE THE DIVER\BepInEx\interop\UnityEngine.CoreModule.dll" Private="false" />
    <Reference Include="UnityEngine.IMGUIModule" HintPath="..\DAVE THE DIVER\BepInEx\interop\UnityEngine.IMGUIModule.dll" Private="false" />
    <Reference Include="UnityEngine.TextRenderingModule" HintPath="..\DAVE THE DIVER\BepInEx\interop\UnityEngine.TextRenderingModule.dll" Private="false" />
  </ItemGroup>

  <Target Name="Deploy" AfterTargets="Build" Condition="'$(DeployPlugin)' != 'false'">
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="..\DAVE THE DIVER\BepInEx\plugins\DaveTheDiverMP" />
  </Target>
</Project>
